[package]
name = "ABC065"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "b"
path = "b-train.rs"

[dependencies]
proconio = "0.4.3"

