[package]
name = "ABC141"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "c"
path = "c-train.rs"

[[bin]]
name = "d"
path = "d-train.rs"

[dependencies]
proconio = "0.4.3"

